---
title: "CV [jp]"
---

## 経歴
### 職歴
- **2025.04-現在 国立研究開発法人産業技術総合研究所 エネルギー・環境領域 安全科学研究部門 社会とLCA研究グループ【研究グループ長】**
- 2023.04-2025.03 国立研究開発法人産業技術総合研究所 エネルギー・環境領域 安全科学研究部門 環境暴露モデリンググループ【主任研究員】
- 2020.02-2023.03 国立研究開発法人産業技術総合研究所 エネルギー・環境領域 安全科学研究部門 リスク評価戦略グループ【主任研究員】
- 2019.02-2020.01 国立研究開発法人産業技術総合研究所 エネルギー・環境領域 研究戦略部 研究企画室【企画主幹】
  - （兼務）国立研究開発法人産業技術総合研究所 エネルギー・環境領域 安全科学研究部門 リスク評価戦略グループ【研究グループ付】
- 2015.04-2019.01 国立研究開発法人産業技術総合研究所 エネルギー・環境領域 安全科学研究部門 リスク評価戦略グループ【主任研究員】
- 2013.10-2015.03 独立研究開発法人産業技術総合研究所 安全科学研究部門 リスク評価戦略グループ【主任研究員】
- 2011.04-2013.09 独立研究開発法人産業技術総合研究所 安全科学研究部門 リスク評価戦略グループ【研究員】
- 2010.04-2011.03 九州大学 イノベーション人材養成センター【特別研究員】
- 2009.11-2010.03 独立研究開発法人産業技術総合研究所 産学官連携推進部門 関西産学官連携センター 組込みシステム技術連携研究体【特別研究員】
- 2009.04-2019.10 日本学術振興会特別研究員(PD)

### 客員等
- **2024.09-現在 東京理科大学 創造理工学部【客員准教授】**
- **2024.04-現在 九州産業大学付属 九州産業高等学校【特別選抜アドバイザー】**
- **2016.08-現在 静岡県立大学 薬学部 衛生分子毒性学分野【客員共同研究員】**
- 2016.04-2024.09 早稲田大学 先端理工学術院【客員講師】

## 学歴
- 2006.04-2009.03 九州大学大学院 数理学府 数理学専攻（2009.03.25 博士（機能数理学）取得）
- 2004.04-2006.03 早稲田大学大学院 理工学研究科 物理学及応用物理学専攻（2006.03.15 修士（理学）取得）
- 2000.04-2004.03 早稲田大学 理工学部 応用物理学科（2004.03.15 学士（工学）取得）
- 2000.03 東京都立西高等学校 卒業

## 受賞
- The 21th ANQ Congress 2023  Best Paper Award，2023-12-11
- Kazuma Morita, Shizu Itaka, Jun-ichi Takesita, and Tomomichi Suzuki, Evaluation of Methods for Estimating Measurement Precision.
- 令和4年度産業標準化事業表彰・産業技術環境局長表彰・国際標準化奨励者表彰，2022.10（経済産業省のニュースリリースページ、産総研のウェブページ）
- 2022年度日本毒性学会田邉賞，2022.06（静岡県立大学薬学部・薬学研究院のウェブページ）
  - Yuki Shimizu, Takamitsu Sasaki, Eri Yonekawa, Hirokazu Yamazaki, Rui Ogura, Michiko Watanabe, Takuomi Hosaka, Ryota Shizu, Jun-ichi Takeshita, and Kouichi Yoshinari, Association of CYP1A1 and CYP1B1 inhibition in vitro assays with drug-induced liver injury, The Journal of Toxicological Science, 46(4) (2020), 167–176.
